config/routes.rb
Rails.application.routes.draw do
  resources :workers
  #get 'welcome/index'



  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:nombre, :rut, :direccion, :telefono, :mail, :equipo, :jefe)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!Doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
<title>INSAC</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

 <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>




</head>
<body>
<nav class="blue-grey darken-3">
  <div class="nav-wrapper container"><a class="brand-logo right" ><span style="color: #FFBA22">INSAC</span></a>


    <ul id="slide-out" class="side-nav">
  
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
          <li>
            <a class="collapsible-header">Trabajadores</a>
            <div class="collapsible-body">
              <ul>
                <li><a href="#!">Ingresar</a></li>
                <li><a href="#!">Ingresar</a></li>
                <li><a href="#!">Eliminar</a></li>
              </ul>
            </div>
          </li>
          <li>
            <a class="collapsible-header">Asistencia</a>
            <div class="collapsible-body">
              <ul>
                <li><a href="#!">Ingresar</a></li>
                <li><a href="#!">Editar</a></li>
                <li><a href="#!">Buscar</a></li>
              </ul>
            </div>
          </li>
                    <li>
            <a class="collapsible-header">Informes</a>
            <div class="collapsible-body">
              <ul>
                <li><a href="#!">Crear</a></li>
                <li><a href="#!">Editar</a></li>
                <li><a href="#!">Buscar</a></li>
              </ul>
            </div>
          </li>
        </ul>
      </li>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i style="color: #FFBA22">Menu Principal</i></a>
          
  </div>
</nav>

<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>






  <script>
    $(document).ready(function(){
      $('dropdown-button').dropdown();
    });
  </script>


<%= yield %>


        
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/workers/_form.html.erb
<%= form_for(worker) do |f| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :rut %>
    <%= f.number_field :rut %>
  </div>

  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>

  <div class="field">
    <%= f.label :telefono %>
    <%= f.text_field :telefono %>
  </div>

  <div class="field">
    <%= f.label :mail %>
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :equipo %>
    <%= f.text_field :equipo %>
  </div>

  <div class="field">
    <%= f.label :jefe %>
    <%= f.text_field :jefe %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reg&iactute;strate</title>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="css/style.css" media="screen,projection">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>




<%= form_for(@worker) do |f| %>
    <% @worker.errors.full_messages.each do |message| %>
      <div class="be-red white top-space">
           *<%= message %>
      </div>
    <%end%>


<div class="container">
    <div class="row">
    <div class="col s12 m12 l12">
      <div id="form-login">
        
          <div class="row">
            <div class="blue-grey darken-3">
              <h5 class="center login-title" style="color: #FFBA22">Editar Trabajador</h5>
            </div>
          </div>
          </div>




            <div class="row">
            <div class="input-field col s6">
              <label for="name">Nombre</label>
             <%=f.text_field :nombre%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Rut</label>
              <%=f.text_field :rut %>
            </div>            
          </div>

                <div class="row">
            <div class="input-field col s6">
              <label for="name">Direccion</label>
             <%=f.text_field :direccion%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Telefono</label>
              <%=f.text_field :telefono %>
            </div>            
          </div>

                 <div class="row">
            <div class="input-field col s6">
              <label for="name">Equipo</label>
             <%=f.text_field :equipo%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Jefe</label>
              <%=f.text_field :jefe %>
            </div>            
          </div>


          <div class="row">
            <div class="input-field col s12">
              <label for="email">Correo</label>
               <%=f.text_field :mail %>
            </div>
          </div>

           <div class="row">
            <div class="col s12">
              <%=f.submit "Guardar" ,class:"btn center-align"  %>
            </div>
          </div>

   </div>

             


   

 <%end%>


</body>
</html>
<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
    <table class="highlight">
        <thead>
          <tr>
              <th data-field="id">Nombre</th>
              <th data-field="name">Rut</th>
              <th data-field="price">Equipo</th>
          </tr>
        </thead>



<% @workers.each do |worker| %>


       <tbody>
          <tr>
            <td><%= link_to worker.nombre, worker %></td>
            <td><%= worker.rut %></td>
            <td><%= worker.equipo %></td>
            <td ><%= link_to "Eliminar", worker, method: :delete %></td>
          </tr>

        </tbody>



<%end%>

      </table>

app/views/workers/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reg&iactute;strate</title>

</head>
<body>




<%= form_for(@worker) do |f| %>
    <% @worker.errors.full_messages.each do |message| %>
      <div class="be-red white top-space">
           *<%= message %>
      </div>
    <%end%>


   <div class="container">
    <div class="row">
    <div class="col s12 m12 l12">
      <div id="form-login">
        
          <div class="row">
            <div class="blue-grey darken-3">
              <h5 class="center login-title" style="color: #FFBA22">Agregar Trabajador</h5>
            </div>
          </div>




            <div class="row">
            <div class="input-field col s6">
              <label for="name">Nombre</label>
             <%=f.text_field :nombre%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Rut</label>
              <%=f.text_field :rut %>
            </div>            
          </div>

                <div class="row">
            <div class="input-field col s6">
              <label for="name">Direccion</label>
             <%=f.text_field :direccion%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Telefono</label>
              <%=f.text_field :telefono %>
            </div>            
          </div>

                 <div class="row">
            <div class="input-field col s6">
              <label for="name">Equipo</label>
             <%=f.text_field :equipo%>
            </div>  
            <div class="input-field col s6">
              <label for="lastname">Jefe</label>
              <%=f.text_field :jefe %>
            </div>            
          </div>


          <div class="row">
            <div class="input-field col s12">
              <label for="email">Correo</label>
               <%=f.text_field :mail %>
            </div>
          </div>

           <div class="row">
            <div class="col s12">
              <%=f.submit "Guardar" ,class:"btn center-align"  %>
            </div>
          </div>

   </div>

             


   

 <%end%>


</body>
</html>

app/views/workers/show.html.erb
<!DOCTYPE html>
<html>
<head>




<meta charset="UTF-8"> 

<link type="text/css" rel="stylesheet" href="styleShow.css">
<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>


</head>
<body id="top">
<div id="cv" >
  <div class="mainDetails">
    
    <div id="name">
      <h1 class="quickFade delayTwo"><%= @worker.nombre %></h1>
      <h2 class="quickFade delayThree"><%=@worker.equipo %></h2>
    </div>
    
    <div id="contactDetails" class="quickFade delayFour">
      <ul>
        <li>Email: <%= @worker.mail %></li>
        
        <li>Telefono: <%= @worker.telefono %></li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
  
  <div id="mainArea" class="quickFade delayFive">
    <section>
      <article>
        <div class="sectionTitle">
          <h1>Cedula Identidad</h1>
        </div>
        
        <div class="sectionContent">
          <h2> <%=@worker.rut %></h2>
        </div>
      </article>
      <div class="clear"></div>
    </section>
    
    
    <section>
      <div class="sectionTitle">
        <h1>Direccion</h1>
      </div>
      
      <div class="sectionContent">
        
          <h2><%=@worker.direccion %></h2>
          
      </div>
      <div class="clear"></div>
    </section>
    
    
    <section>
      <div class="sectionTitle">
        <h1>Jefe</h1>
      </div>

      <div class="sectionContent">

      <h2><%=@worker.jefe %></h2>
      
      </div>

      <div class="clear"></div>
    </section>
    
    
    
    
  </div>

    <%= button_to "Editar", edit_worker_path(@worker),
      :class => "waves-effect waves-light btn", :method => :get %>

    


</div>

</body>
</html>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>